name: .NET Core - Build & Test

on:
  push:
    branches: [ master ]
    paths-ignore:
    - '**/README.md'
    - '**/*.yml'
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest 
    defaults:
      run:
        working-directory: Cli.Mail     

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
      
    - name: Build
      run: dotnet build
            
    - name: Install Coverlet
      run: dotnet tool install -g coverlet.console

    - name: Test
      run: coverlet ./Cli.Mail.Tests/bin/Debug/netcoreapp3.1/Cli.Mail.Tests.dll -t dotnet -a "test --no-build" -f opencover

    - name: Upload report to Codecov
      uses: codecov/codecov-action@v1.0.13
